package hashpackage;

import java.util.Scanner;

public class HashMain {

    public static void main(String[] args) {

        GetMD5 getMD5 = new GetMD5();

        Scanner scanner = new Scanner(System.in);
        System.out.println("Metni daxil edin");
        String s = scanner.nextLine();
        System.out.println("Your Hashcode generated by MD5 is: " + getMD5.getMd5(s));
    }
}
